baseURL = '/'
languageCode = 'en-us'
title = 'Pink Pussy Cats - Live Music'
theme = 'spectral'

[params]
fancyTitle = "Pink Pussy Cats<br> <img src='/img/Banner.svg' width='80%' height='80%'/>" # title for frontpage, may include image
copyright = "PPC"
description = '''
Live Cover-Musik made in Spaichingen

'''
#startbuttonText = "Activate"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
images = ["img/PPC_black.svg"]

[[params.menu.main]]
url = ''
title = "Home"

[[params.menu.main]]
url = '/home'
title = "Events"

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = "@pinkpussycats5808"
instagram = "bass_man_ppc"
dribble = ""

[params.one]
enable = true
body= '''
PPC - Die Haus- und Hofband des Indiacaclubs Spaichingen!
---
“Anybody can play. The note is only 20 percent.  
The attitude of the motherfucker who plays it is 80 percent.”  
Miles Davis
'''

[params.cta]
enable = true
title = "Downloads"
body = '''
Infos für Techniker und Presse.
'''

[[params.cta.link]]
href = "rider/PPC-Stageplan.pdf"
text = "Tech Rider"
special = false

[[params.cta.link]]
href = "press/PressKit.pdf"
text = "Press (pdf)"
special = false

[[params.cta.link]]
href = "press/PPC_PressKit.docx"
text = "Press (docx)"
special = false

[params.two]
enable = true

[[params.two.section]]
img = "img/Band3.jpg"
title = 'Wir sind'
body = '''
Sasa Sepi (Bass)  
Matthias Butsch (Gesang)  
Meik Morlock (Schlagzeug)  
Jörn Hauser (Gitarre)  
Steffen Scheffler (Keyboard) 

Ehemalige:
Markus Luttmann (Gitarre)
'''

[[params.two.section]]
img = "img/PPC_Proberaum.jpg"
title = 'Social Media'
body = '''
{{< youtube id="2P0XxF1_ozo" title="A New Hugo Site in Under Two Minutes" >}}

Folgt uns auf [Youtube](https://www.youtube.com/@pinkpussycats5808 "PPC")!
'''

[[params.two.section]]
#img = "img/PPC_Proberaum.jpg"
title = 'Kontakt'
body = '''
##### Booking
Matthias Butsch (+49 174 3040726)  
##### Technische Fragen
Jörn Hauser (+49 176 82059964)
'''